### ISSUE TITLE
Could you add our work?

### ISSUE THREAD

**Issue by sharlingw** [Kedreamix/Awesome-Talking-Head-Synthesis#2]
The title of our paper is "Pose-Aware 3D Talking Face Synthesis using Geometry-guided Audio-Vertices Attention" at https://ieeexplore.ieee.org/abstract/document/10452856. And our github project URL is https://github.com/sharlingw/PATS.

**Comment by Kedreamix** [comment]
Yes, of course! I will update it soon.

**Comment by sharlingw** [comment]
> Yes, of course! I will update it soon.

Thank you so much.
