### ISSUE TITLE
EMO did not disclose any code

### ISSUE THREAD

**Issue by zhangchn** [Kedreamix/Awesome-Talking-Head-Synthesis#3]
[EMO] [EMO: Emote Portrait Alive - Generating Expressive Portrait Videos with Audio2Video Diffusion Model under Weak Conditions](https://arxiv.org/abs/2402.17485v1)

In its github repo (https://github.com/HumanAIGC/EMO), not a single line of code has been provided, yet.

**Comment by lymhust** [comment]
An alternative project EchoMimic is open-sourced
EchoMimic is capable of generating portrait videos not only by audios and facial landmarks individually, but also by a combination of both audios and selected facial landmarks.
Project link: https://badtobest.github.io/echomimic.html
GitHub link: https://github.com/BadToBest/EchoMimic
![image](https://github.com/Kedreamix/Awesome-Talking-Head-Synthesis/assets/18476076/ffd8f614-0f13-45d3-926c-610bfaa51eb0)

https://github.com/Kedreamix/Awesome-Talking-Head-Synthesis/assets/18476076/3a5b9b45-523a-46ee-8d48-ec9414a72c2b

**Comment by Kedreamix** [comment]
Although the EMO GitHub repository (https://github.com/HumanAIGC/EMO) does not currently contain any code, you may want to check out similar open-source projects such as Hallo, Echo, and Musetalk. These projects have also made significant advancements in generating expressive portrait videos and have released their code for research and reference.
