### ISSUE TITLE
EchoMimic is open-sourced

### ISSUE THREAD

**Issue by lymhust** [Kedreamix/Awesome-Talking-Head-Synthesis#4]
EchoMimic is capable of generating portrait videos not only by audios and facial landmarks individually, but also by a combination of both audios and selected facial landmarks.
Project link: https://badtobest.github.io/echomimic.html
GitHub link: https://github.com/BadToBest/EchoMimic
![image](https://github.com/Kedreamix/Awesome-Talking-Head-Synthesis/assets/18476076/eda4b270-ea14-4915-949c-ac36aa3169f0)

https://github.com/Kedreamix/Awesome-Talking-Head-Synthesis/assets/18476076/bdbd8049-ef87-4d0d-a160-9331499fb148

**Comment by Kedreamix** [comment]
Thanks! I will update it soon.
